blank_issues_enabled: false

contact_links:
  - name: Project Discussion
    url: https://github.com/gohanlon/swift-memberwise-init-macro/discussions
    about: Library Q&A, ideas, and more
  - name: README
    url: https://github.com/gohanlon/swift-memberwise-init-macro
    about: Read the README
